# Create Consoles
Console.create(name: "PlayStation", manufacturer: "Sony", release_date: "Dec. 1994")
Console.create(name: "PlayStation 2", manufacturer: "Sony", release_date: "Mar. 2000")
Console.create(name: "PlayStation 3", manufacturer: "Sony", release_date: "Nov. 2006")
Console.create(name: "PlayStation 4", manufacturer: "Sony", release_date: "Nov. 2013")
Console.create(name: "PlayStation 5", manufacturer: "Sony", release_date: "Nov. 2020")

Console.create(name: "Xbox", manufacturer: "Microsoft", release_date: "Nov. 2001")
Console.create(name: "Xbox 360", manufacturer: "Microsoft", release_date: "Nov. 2005")
Console.create(name: "Xbox One", manufacturer: "Microsoft", release_date: "Nov. 2013")
Console.create(name: "Xbox Series S", manufacturer: "Microsoft", release_date: "Nov. 2020")
Console.create(name: "Xbox Series X", manufacturer: "Microsoft", release_date: "Nov. 2020")

Console.create(name: "NES", manufacturer: "Nintendo", release_date: "Jul. 1983")
Console.create(name: "Super NES", manufacturer: "Nintendo", release_date: "Nov. 1990")
Console.create(name: "N64", manufacturer: "Nintendo", release_date: "Jun. 1996")
Console.create(name: "GameCube", manufacturer: "Nintendo", release_date: "Nov. 2001")
Console.create(name: "Wii", manufacturer: "Nintendo", release_date: "Nov. 2005")
Console.create(name: "Switch", manufacturer: "Nintendo", release_date: "Mar. 2017")

Console.create(name: "Dreamcast", manufacturer: "Sega", release_date: "Nov. 1998")
Console.create(name: "Saturn", manufacturer: "Sega", release_date: "Nov. 1994")

# Create Games
Game.create(name: "Call of Duty", publisher: "Activision", developer: "Infinity Ward", release_date: "2003")
Game.create(name: "Call of Duty 2", publisher: "Activision", developer: "Infinity Ward", release_date: "2005")
Game.create(name: "Call of Duty 3", publisher: "Activision", developer: "Treyarch", release_date: "2006")
Game.create(name: "Call of Duty 4: Modern Warfare", publisher: "Activision", developer: "Infinity Ward", release_date: "2007")
Game.create(name: "Call of Duty: World at War", publisher: "Activision", developer: "Treyarch", release_date: "2008")
Game.create(name: "Call of Duty: Modern Warfare 2", publisher: "Activision", developer: "Infinity Ward", release_date: "2009")
Game.create(name: "Call of Duty: Black Ops", publisher: "Activision", developer: "Treyarch", release_date: "2010")
Game.create(name: "Call of Duty: Modern Warfare 3", publisher: "Activision", developer: "Infinity Ward", release_date: "2011")
Game.create(name: "Call of Duty: Black Ops 2", publisher: "Activision", developer: "Treyarch", release_date: "2012")
Game.create(name: "Call of Duty: Ghosts", publisher: "Activision", developer: "Infinity Ward", release_date: "2013")
Game.create(name: "Call of Duty: Black Ops 3", publisher: "Activision", developer: "Treyarch", release_date: "2015")
Game.create(name: "Call of Duty: Infinite Warfare", publisher: "Activision", developer: "Infinity Ward", release_date: "2016")
Game.create(name: "Call of Duty: WWII", publisher: "Activision", developer: "Sledgehammer Games", release_date: "2017")
Game.create(name: "Call of Duty: Black Ops 4", publisher: "Activision", developer: "Treyarch", release_date: "2018")
Game.create(name: "Call of Duty: Black Ops Cold War", publisher: "Activision", developer: "Treyarch", release_date: "2020")

Game.create(name: "Final Fantasy", publisher: "Square", developer: "Square", release_date: "1987")
Game.create(name: "Final Fantasy II", publisher: "Square", developer: "Square", release_date: "1988")
Game.create(name: "Final Fantasy III", publisher: "Square", developer: "Square", release_date: "1990")
Game.create(name: "Final Fantasy IV", publisher: "Square", developer: "Square", release_date: "1991")
Game.create(name: "Final Fantasy V", publisher: "Square", developer: "Square", release_date: "1992")
Game.create(name: "Final Fantasy VI", publisher: "Square", developer: "Square", release_date: "1994")
Game.create(name: "Final Fantasy VII", publisher: "PlayStation", developer: "Square", release_date: "1997")
Game.create(name: "Final Fantasy VIII", publisher: "Square", developer: "Square", release_date: "1999")
Game.create(name: "Final Fantasy IX", publisher: "Square", developer: "Square", release_date: "2000")
Game.create(name: "Final Fantasy X", publisher: "Square", developer: "Square", release_date: "2001")
Game.create(name: "Final Fantasy XI", publisher: "PlayStation", developer: "Square Enix", release_date: "2002")
Game.create(name: "Final Fantasy XII", publisher: "Square Enix", developer: "Square Enix", release_date: "2006")
Game.create(name: "Final Fantasy XIII", publisher: "Square Enix", developer: "Square Enix", release_date: "2009")
Game.create(name: "Final Fantasy XIV: Online", publisher: "Square Enix", developer: "Square Enix", release_date: "2010")
Game.create(name: "Final Fantasy XIV: A Relm Reborn", publisher: "Square Enix", developer: "Square Enix", release_date: "2013")
Game.create(name: "Final Fantasy XV", publisher: "Square Enix", developer: "Square Enix", release_date: "2016")

# Create Users

u1 = User.create(username: "JRPG_Lover", password: "japan")
u2 = User.create(username: "COD_Fan_Boy", password: "ak47")
u3 = User.create(username: "Casual_Gamer", password: "farmvil")

# Create Collections
c1 = Collection.create(name: "JRPGS", user_id: User.first.id, console_id: Console.find(5).id)
c2 = Collection.create(name: "Best Shooters Ever", user_id: User.find(2).id, console_id: Console.find(4).id)
c3 = Collection.create(name: "Fun Games :)", user_id: User.find(3).id, console_id: Console.find_by(name: "Switch").id)

c1.games << Game.find(16) << Game.find(17) << Game.find(18) << Game.find(19) << Game.find(20) << Game.find(21) << Game.find(22) << Game.find(23) << Game.find(24) << Game.find(25) << Game.find(26) << Game.find(27) << Game.find(28) << Game.find(29) << Game.find(30)
c2.games << Game.find(1) << Game.find(2) << Game.find(3) << Game.find(4) << Game.find(5) << Game.find(6) << Game.find(7) << Game.find(8) << Game.find(9) << Game.find(10) << Game.find(11) << Game.find(12) << Game.find(13) << Game.find(14) << Game.find(15)
c3.games << Game.find(30)